version: '3.8'

services:
    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        image: cosmicsatish/fastapi
        ports:
            - "8000:8000"
    streamlit:
        build:
            context: ./streamlit_app
            dockerfile: Dockerfile
        image: cosmicsatish/streamlit
        ports:
            - "8501:8501"
        environment:
            - API_URL=http://fastapi:8000
        depends_on:
            - fastapi